name: ekipma_api
description: Dart gRPC client
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.2.0
  grpc: ^3.2.4
  protobuf: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
