// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.0
// source: protos/record.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RecordServiceClient is the client API for RecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecordServiceClient interface {
	CreateRecords(ctx context.Context, in *Record, opts ...grpc.CallOption) (RecordService_CreateRecordsClient, error)
	RecentRecords(ctx context.Context, in *Last, opts ...grpc.CallOption) (RecordService_RecentRecordsClient, error)
	DeleteRecord(ctx context.Context, in *IdInput, opts ...grpc.CallOption) (*Empty, error)
	// -- pay --
	// integrity - probably a button in mobile client settings
	PayIds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Integrity, error)
	LostPays(ctx context.Context, in *Integrity, opts ...grpc.CallOption) (RecordService_LostPaysClient, error)
	// -- turn --
	SubmitTurn(ctx context.Context, in *IdInput, opts ...grpc.CallOption) (*Turn, error)
}

type recordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecordServiceClient(cc grpc.ClientConnInterface) RecordServiceClient {
	return &recordServiceClient{cc}
}

func (c *recordServiceClient) CreateRecords(ctx context.Context, in *Record, opts ...grpc.CallOption) (RecordService_CreateRecordsClient, error) {
	stream, err := c.cc.NewStream(ctx, &RecordService_ServiceDesc.Streams[0], "/ekipma.api.record.RecordService/CreateRecords", opts...)
	if err != nil {
		return nil, err
	}
	x := &recordServiceCreateRecordsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RecordService_CreateRecordsClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type recordServiceCreateRecordsClient struct {
	grpc.ClientStream
}

func (x *recordServiceCreateRecordsClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recordServiceClient) RecentRecords(ctx context.Context, in *Last, opts ...grpc.CallOption) (RecordService_RecentRecordsClient, error) {
	stream, err := c.cc.NewStream(ctx, &RecordService_ServiceDesc.Streams[1], "/ekipma.api.record.RecordService/RecentRecords", opts...)
	if err != nil {
		return nil, err
	}
	x := &recordServiceRecentRecordsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RecordService_RecentRecordsClient interface {
	Recv() (*Record, error)
	grpc.ClientStream
}

type recordServiceRecentRecordsClient struct {
	grpc.ClientStream
}

func (x *recordServiceRecentRecordsClient) Recv() (*Record, error) {
	m := new(Record)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recordServiceClient) DeleteRecord(ctx context.Context, in *IdInput, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/ekipma.api.record.RecordService/DeleteRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) PayIds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Integrity, error) {
	out := new(Integrity)
	err := c.cc.Invoke(ctx, "/ekipma.api.record.RecordService/PayIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recordServiceClient) LostPays(ctx context.Context, in *Integrity, opts ...grpc.CallOption) (RecordService_LostPaysClient, error) {
	stream, err := c.cc.NewStream(ctx, &RecordService_ServiceDesc.Streams[2], "/ekipma.api.record.RecordService/LostPays", opts...)
	if err != nil {
		return nil, err
	}
	x := &recordServiceLostPaysClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RecordService_LostPaysClient interface {
	Recv() (*Pay, error)
	grpc.ClientStream
}

type recordServiceLostPaysClient struct {
	grpc.ClientStream
}

func (x *recordServiceLostPaysClient) Recv() (*Pay, error) {
	m := new(Pay)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *recordServiceClient) SubmitTurn(ctx context.Context, in *IdInput, opts ...grpc.CallOption) (*Turn, error) {
	out := new(Turn)
	err := c.cc.Invoke(ctx, "/ekipma.api.record.RecordService/SubmitTurn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordServiceServer is the server API for RecordService service.
// All implementations must embed UnimplementedRecordServiceServer
// for forward compatibility
type RecordServiceServer interface {
	CreateRecords(*Record, RecordService_CreateRecordsServer) error
	RecentRecords(*Last, RecordService_RecentRecordsServer) error
	DeleteRecord(context.Context, *IdInput) (*Empty, error)
	// -- pay --
	// integrity - probably a button in mobile client settings
	PayIds(context.Context, *Empty) (*Integrity, error)
	LostPays(*Integrity, RecordService_LostPaysServer) error
	// -- turn --
	SubmitTurn(context.Context, *IdInput) (*Turn, error)
	mustEmbedUnimplementedRecordServiceServer()
}

// UnimplementedRecordServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRecordServiceServer struct {
}

func (UnimplementedRecordServiceServer) CreateRecords(*Record, RecordService_CreateRecordsServer) error {
	return status.Errorf(codes.Unimplemented, "method CreateRecords not implemented")
}
func (UnimplementedRecordServiceServer) RecentRecords(*Last, RecordService_RecentRecordsServer) error {
	return status.Errorf(codes.Unimplemented, "method RecentRecords not implemented")
}
func (UnimplementedRecordServiceServer) DeleteRecord(context.Context, *IdInput) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRecord not implemented")
}
func (UnimplementedRecordServiceServer) PayIds(context.Context, *Empty) (*Integrity, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PayIds not implemented")
}
func (UnimplementedRecordServiceServer) LostPays(*Integrity, RecordService_LostPaysServer) error {
	return status.Errorf(codes.Unimplemented, "method LostPays not implemented")
}
func (UnimplementedRecordServiceServer) SubmitTurn(context.Context, *IdInput) (*Turn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTurn not implemented")
}
func (UnimplementedRecordServiceServer) mustEmbedUnimplementedRecordServiceServer() {}

// UnsafeRecordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecordServiceServer will
// result in compilation errors.
type UnsafeRecordServiceServer interface {
	mustEmbedUnimplementedRecordServiceServer()
}

func RegisterRecordServiceServer(s grpc.ServiceRegistrar, srv RecordServiceServer) {
	s.RegisterService(&RecordService_ServiceDesc, srv)
}

func _RecordService_CreateRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Record)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordServiceServer).CreateRecords(m, &recordServiceCreateRecordsServer{stream})
}

type RecordService_CreateRecordsServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type recordServiceCreateRecordsServer struct {
	grpc.ServerStream
}

func (x *recordServiceCreateRecordsServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

func _RecordService_RecentRecords_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Last)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordServiceServer).RecentRecords(m, &recordServiceRecentRecordsServer{stream})
}

type RecordService_RecentRecordsServer interface {
	Send(*Record) error
	grpc.ServerStream
}

type recordServiceRecentRecordsServer struct {
	grpc.ServerStream
}

func (x *recordServiceRecentRecordsServer) Send(m *Record) error {
	return x.ServerStream.SendMsg(m)
}

func _RecordService_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ekipma.api.record.RecordService/DeleteRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).DeleteRecord(ctx, req.(*IdInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_PayIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).PayIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ekipma.api.record.RecordService/PayIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).PayIds(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecordService_LostPays_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Integrity)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecordServiceServer).LostPays(m, &recordServiceLostPaysServer{stream})
}

type RecordService_LostPaysServer interface {
	Send(*Pay) error
	grpc.ServerStream
}

type recordServiceLostPaysServer struct {
	grpc.ServerStream
}

func (x *recordServiceLostPaysServer) Send(m *Pay) error {
	return x.ServerStream.SendMsg(m)
}

func _RecordService_SubmitTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServiceServer).SubmitTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ekipma.api.record.RecordService/SubmitTurn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServiceServer).SubmitTurn(ctx, req.(*IdInput))
	}
	return interceptor(ctx, in, info, handler)
}

// RecordService_ServiceDesc is the grpc.ServiceDesc for RecordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ekipma.api.record.RecordService",
	HandlerType: (*RecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteRecord",
			Handler:    _RecordService_DeleteRecord_Handler,
		},
		{
			MethodName: "PayIds",
			Handler:    _RecordService_PayIds_Handler,
		},
		{
			MethodName: "SubmitTurn",
			Handler:    _RecordService_SubmitTurn_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CreateRecords",
			Handler:       _RecordService_CreateRecords_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecentRecords",
			Handler:       _RecordService_RecentRecords_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "LostPays",
			Handler:       _RecordService_LostPays_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/record.proto",
}
